### ISSUE TITLE
淘宝的无法授权成功

### ISSUE THREAD

**Issue by X-Bird** [chekun/Oauth2-SocialAuth-for-CodeIgniter#1]
你好，你的example代码无法让淘宝的授权成功，登陆回调后提示 Exception error

**Comment by chekun** [comment]
Yes,确实如此，回头我看一下，你有时间也可以帮我修改一下，呵呵。

**Comment by X-Bird** [comment]
原来你看见了。。。那好吧。。。我还去你腾讯微博烦你～ 没看见github上的回复～ 好吧～ 我知道你知道了～ 
Sorry 不是故意烦你的～

**Comment by chekun** [comment]
呵呵，没什么好麻烦的，没事儿，多谢你的反馈
