### ISSUE TITLE
QQ登陆或者腾讯微博登陆都为操作失败 Exception: Unknown Error.

### ISSUE THREAD

**Issue by allanguys** [chekun/Oauth2-SocialAuth-for-CodeIgniter#2]
QQ登陆或者腾讯微博登陆
都为操作失败 Exception: Unknown Error.

![Uploading err.png . . .]()

麻烦作者看一下

**Comment by chekun** [comment]
http://oauth24codeigniter.sinaapp.com/
这里我登陆没有问题，如果有问题也有可能是应用没有审核导致的，你可以下载代码自行申请一个应用来测试下。

**Comment by allanguys** [comment]
本地登陆回调会出现这样的问题，到服务器上就可以了。本地调试的时候是需要注意什么内容吗？

**Comment by chekun** [comment]
有些平台不支持本地调试哦
