### ISSUE TITLE
一次离奇的案件！

### ISSUE THREAD

**Issue by 18601673727** [chekun/Oauth2-SocialAuth-for-CodeIgniter#3]
作者您好，首先感谢您的优秀类库，它给我带来了很大的帮助！
但在使用过程中，碰到了一个问题：

我有两个站点a,b，分别申请了不同的weibo api
a站点微博登录成功了，然后把整个项目复制一份放到b站点，
修改好相应的参数（config/config.php, config/oauth2.php）之后，
在b站点微博登录时却报

“你所访问的站点在新浪微博的认证失败(error:invalid_request)”

请问应该怎样解决，谢谢!

＊ 两台服务器环境php皆是5.3.1x
＊ 操作系统a是centos，b是win2003
＊ qq也不行报：redirect uri is illegal(100010)
＊ 如需了解详细站点地址可私信

**Comment by chekun** [comment]
授权回调地址写错了吧

**Comment by 18601673727** [comment]
@chekun 请问回调地址写在哪里？

**Comment by chekun** [comment]
在你申请的应用里的

**Comment by 18601673727** [comment]
@chekun
weibo 我一直找不到哪里好写回调（网站接入）；
qq倒是有   例如我的域名是www.example.com  那么我在回调里写 “www.example.com;example.com” 为何还是错的？

**Comment by chekun** [comment]
不是吧，应用信息高级信息里面啊。。。
![2013-10-24 2 10 58](https://f.cloud.github.com/assets/1967804/1396783/2cf0b05c-3c73-11e3-85f2-f05cc1033f9e.png)

**Comment by 18601673727** [comment]
我把网站接入删了，换成了跟你截图中一样的应用类型，并填好了回调地址，
但是...这下又让我联系开发小助手了...而不是联系我本人的微博账号了...

不如我们从qq入手排查吧...qq没有这么复杂...回调地址跟本身地址一样就行...可为何还是redirect uri is illegal(100010)...

**Comment by chekun** [comment]
你先了解一下，什么是oauth2的回调地址(redirect uri)吧，这个不是随便设置的

**Comment by 18601673727** [comment]
我随便设置居然a站点的weibo、qq还能登录成功？我是来逗你玩的么？

**Comment by chekun** [comment]
请发a，b站点应用设置，回调地址设置，以及线上应用地址。

**Comment by 18601673727** [comment]
好，请给我一个你的邮箱，后面通过邮件沟通吧

**Comment by chekun** [comment]
邮箱点我头像看。

**Comment by 18601673727** [comment]
发送成功，请查收
