### ISSUE TITLE
加载oauth2类库的问题

### ISSUE THREAD

**Issue by mytharcher** [chekun/Oauth2-SocialAuth-for-CodeIgniter#5]
感谢作者的插件，但是不知道是不是我使用的姿势不对，安装说明在controller里加载oauth2或者直接在`autoload`里加载，始终都无法调用`OAuth2`类上的`provider`静态方法。

当我在controller中`var_dump($this->oauth2)`时，得到的是以下结果：

```
object(OAuth2)#14 (0) { } 
```

对象上并没有类上的静态方法。于是怀疑是否是因为静态方法无法加载，google之找到一个帖子[Use a static method from a personal library without instance](http://ellislab.com/forums/viewthread/73583/)，里面说通过`libraries`加载的类库都会自动实例化成一个对象，不知道是否是这个问题？

但是我照老外说的改成`helper`方式加载也不行。

我使用的CI版本是2.1.x。

**Comment by chekun** [comment]
See https://github.com/chekun/Oauth2-SocialAuth-for-CodeIgniter/blob/master/example/application/controllers/sns.php

**Comment by mytharcher** [comment]
我测试了example中的代码是可以运行的，但是按照你的方式将oauth相关文件添加到我项目的`application/libraries`中后就会出现上面说的问题。

我注意到example中的CI版本是`3.0-dev`，是否是版本差异导致？目前官方好像还没有发布这个新版本，我并不清楚其中有哪些比较大的改动。

**Comment by chekun** [comment]
@mytharcher 应该是没有问题的，你报的错误是什么？

**Comment by mytharcher** [comment]
错误就是找不到`$this->oauth2->provider`这个方法，未定义。所以我输出`oauth2`对象得到上面那个结果。后来我自己写了个空的测试类结果也是一样，无法找到对象上的静态方法：

``` php
class Testest {
    public static function test () {}
}
```

所以我觉得应该是CI 2.x加载类库的机制问题，把加载的类都自动实例化了，导致无法使用静态方法（正如我搜到的那个帖子）。

**Comment by mytharcher** [comment]
对不起，我跟踪了下程序，发现我之前的判断有误，静态函数也是可以被调用的。但是当执行到`Provider`类构造函数的最后一句`$this->redirect_uri = site_url(get_instance()->uri->uri_string());`时，`site_url`这个函数好像找不到。

我PHP的版本是`5.4.24`。

**Comment by chekun** [comment]
@mytharcher 在autoload.php里，添加url_helper

**Comment by mytharcher** [comment]
多谢，加载`url`辅助函数后找到原因了，由于我的项目重写了`Session`类导致其中调用`set_userdata`和`userdata`两个方法不兼容。

**Comment by chekun** [comment]
@mytharcher 不客气，定位到原因就好
