### ISSUE TITLE
好像豆瓣 oauth 坏掉了?

### ISSUE THREAD

**Issue by samma835** [chekun/Oauth2-SocialAuth-for-CodeIgniter#6]
Message: file_get_contents(https://www.douban.com/service/auth2/token): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

Filename: oauth2/Provider.php

**Comment by chekun** [comment]
http://oauth24codeigniter.sinaapp.com/ 这里是好的

**Comment by samma835** [comment]
可能是豆瓣对待测试应用和审核通过应用有区别(包括对待 redirect_url). 正式帐号好像不支持通过 file_get_contents http 1.0 的方式去访问 douban 了, 会 403 Forbidden. 

我回头用 curl 重写一下这块的逻辑试一下.

**Comment by samma835** [comment]
改了一下, work 了

https://gist.github.com/bullda/52f93c4d9b93d29e1593

**Comment by chekun** [comment]
@bullda :+1:
